# Generated by Django 4.1.7 on 2023-04-17 16:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliopage_skill_socialaccount_socialbutton_work_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialbutton',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='socialbutton',
            name='portfolio',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_buttons', to='portfolio.portfoliopage'),
        ),
        migrations.AddField(
            model_name='socialbutton',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='socialbutton',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialbutton',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
