# Generated by Django 4.1.7 on 2023-04-17 17:20

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_socialbutton_options_socialbutton_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialbutton',
            name='portfolio',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_buttons', to='portfolio.portfoliopage'),
        ),
    ]
