# Generated by Django 4.1.7 on 2023-04-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_socialbutton_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialbutton',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='svg'),
        ),
    ]
