# Generated by Django 4.1.7 on 2023-05-23 21:41

from django.db import migrations


def initial_data(apps, schema_editor):
    ContentType = apps.get_model("contenttypes.ContentType")
    PortfolioPage = apps.get_model("portfolio.PortfolioPage")
    Site = apps.get_model("wagtailcore.Site")

    # Create page content type
    page_content_type, created = ContentType.objects.get_or_create(
        model="portfoliopage", app_label="portfolio"
    )

    try:
        PortfolioPage.objects.get(
            content_type=page_content_type,
            path="00010001",
            depth=2,
            numchild=0,
        )
    except PortfolioPage.DoesNotExist:
        # Update homepage
        page, created = PortfolioPage.objects.update_or_create(
            pk=2,
            title="Portfolio",
            slug="portfolio",
            content_type=page_content_type,
            path="00010001",
            depth=2,
            numchild=0,
            url_path="/portfolio/",
            locale_id=1,
        )

        # Update default site
        Site.objects.update_or_create(
            hostname="localhost", root_page_id=page.id, is_default_site=True
        )


def remove_initial_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0008_portfoliopage_email'),
    ]

    operations = [
        migrations.RunPython(initial_data, remove_initial_data)
    ]
