# Generated by Django 4.1.7 on 2023-05-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20230524_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliopage',
            options={'verbose_name': 'Portfolio page'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={'verbose_name': 'Social button', 'verbose_name_plural': 'Social buttons'},
        ),
        migrations.AlterModelOptions(
            name='socialbutton',
            options={'verbose_name': 'Social button', 'verbose_name_plural': 'Social buttons'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
        migrations.RemoveField(
            model_name='socialbutton',
            name='portfolio',
        ),
    ]
